superlists/urls.py
from django.contrib import admin
from django.urls import re_path, include
from todolists import views
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.home_page, name='home_page'),
    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'/static/favicon.ico')),
    re_path(r'^todolists/', include('todolists.urls')),
]

todolists/urls.py
from django.urls import re_path

from todolists import views

urlpatterns = [
    re_path(r'^new$', views.new_list, name='new_list'),
    re_path(r'^(\d+)/$', views.view_list, name='view_list'),
    re_path(r'^(\d+)/json$', views.json_list, name='json_list'),
    re_path(r'^(\d+)/(\d+)/delete$', views.delete_item, name='delete_item'),
    re_path(r'^(\d+)/delete$', views.delete_list, name='delete_list'),
    re_path(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

todolists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField()
    list = models.ForeignKey(List, on_delete=models.CASCADE, default='')

todolists/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import JsonResponse, Http404

from todolists.models import Item, List


def home_page(request):
    return render(request, "todolists/home.html")


def view_list(request, list_id):
    try:
        list_ = List.objects.get(id=list_id)
        return render(request, "todolists/todolists.html", {'list': list_})
    except List.DoesNotExist:
        return JsonResponse(
            {'result': 404, 'msg': f'List {list_id} does not exist'})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/todolists/%d/' % (list_.id,))


def add_item(request, list_id):
    try:
        list_ = List.objects.get(id=list_id)
        Item.objects.create(text=request.POST['item_text'], list=list_)
        return redirect('/todolists/%d/' % (list_.id,))
    except List.DoesNotExist:
        return JsonResponse(
            {'result': 404, 'msg': f'List {list_id} does not exist'})


def json_list(request, list_id):
    list_ = get_object_or_404(List, id=list_id)
    items = Item.objects.filter(list=list_)
    return JsonResponse(
        {'result': 200, 'msg': [f"id:{item.id}, todoItem:{item.text}" for item in items]})


def delete_item(request, list_id, item_id):
    try:
        list_ = List.objects.get(id=list_id)
        Item.objects.filter(list=list_, id=item_id).delete()
        return redirect('/todolists/%d/' % (list_.id,))
    except List.DoesNotExist:
        return JsonResponse(
            {'result': 404, 'msg': f'List {list_id} does not exist'})


def delete_list(request, list_id):
    try:
        list_ = List.objects.get(id=list_id)
        Item.objects.filter(list=list_).delete()
        List.objects.filter(id=list_id).delete()
    except List.DoesNotExist:
        raise Http404("List does not exist")
    finally:
        return redirect('/')

todolists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Todolists</title>
    <meta name="viewport" content="width=device-width">
    <link href="//cdn.staticfile.org/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/bootstrap/css/custom.css" rel="stylesheet" media="screen">
    <script src="//cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdn.staticfile.org/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">

    <div id="myCarousel" class="carousel slide visible-lg">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0"></li>
            <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>
        <!-- 轮播（Carousel）项目 -->
        <div class="carousel-inner">
            <div class="item">
                <img src="https://static.runoob.com/images/mix/img_fjords_wide.jpg" alt="First slide">
            </div>
            <div class="item">
                <img src="https://static.runoob.com/images/mix/img_nature_wide.jpg" alt="Second slide">
            </div>
            <div class="item">
                <img src="https://static.runoob.com/images/mix/img_mountains_wide.jpg" alt="Third slide">
            </div>
            <div class="item active">
                <img src="/static/dogdog.jpg">
            </div>
        </div>
        <!-- 轮播（Carousel）导航 -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                <form method="POST" action="{% block form_action %}{% endblock %}">
                    <input name="item_text" class="form-control input-lg" id="new_item" placeholder="Enter a to-do item"/>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

</div>
</body>

</html>

todolists/templates/todolists/home.html
{% extends 'base.html' %}

{% block header_text %}New Todolist{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

todolists/templates/todolists/todolists.html
{% extends 'base.html' %}

{% block header_text %}
    Todolist
    <button id="delete_list" type="button" class="btn btn-warning btn-circle" title="删除列表"
            onclick="window.location.href='{% url 'delete_list' list.id %}'">{% csrf_token %}
        <i class="glyphicon glyphicon-remove"></i>
    </button>
{% endblock %}

{% block form_action %}{% url 'add_item' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table table-hover table-striped">
        {% for item in list.item_set.all %}
            <tr>
                <td>
                    {{ forloop.counter }}: {{ item.text }}
                    <button id="delete_item{{ forloop.counter }}" type="button" class="btn btn-warning btn-circle" title="删除待办项"
                            onclick="window.location.href='{% url 'delete_item' list.id item.id %}'">
                        {% csrf_token %}
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}